# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  Major: '1'
  Minor: '0'
  Patch: '0'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
      - job: build
        tasks:
          - task: NuGetCommand@2
              inputs:
                command: pack
                packagesToPack: '**/*.csproj'
                versioningScheme: byPrereleaseNumber
                majorVersion: '$(Major)'
                minorVersion: '$(Minor)'
                patchVersion: '$(Patch)'

